[NbConvertApp] Converting notebook ProcessEimage.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: lsst
root INFO: Loading config overrride file '/opt/lsst/software/stack/stack/miniconda3-4.5.12-1172c30/Linux64/obs_lsstSim/18.1.0/config/processEimage.py'
CameraMapper INFO: Loading exposure registry from /home/kadrlica/notebooks/.beavis/StackClub/ImageProcessing/DATA/registry.sqlite3
root ERROR: Invalid alias: The name clear can't be aliased because it is another magic command.
root ERROR: Invalid alias: The name more can't be aliased because it is another magic command.
root ERROR: Invalid alias: The name less can't be aliased because it is another magic command.
root ERROR: Invalid alias: The name man can't be aliased because it is another magic command.
[NbConvertApp] ERROR | Error while converting 'ProcessEimage.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 408, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 381, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 424, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
args = 'DATA --rerun process-eimage  --id filter=r --show data'
ProcessEimageTask.parseAndRun(args=args.split())

# BUG: the command above exits early, due to a namespace problem:
# /opt/lsst/software/stack/stack/miniconda3-4.3.21-10a4fa6/Linux64/pipe_base/15.0/python/lsst/pipe/base/argumentParser.py in parse_args(self, config, args, log, override)
#     628 
#     629         if namespace.show and "run" not in namespace.show:
# --> 630             sys.exit(0)
------------------

An exception has occurred, use %tb to see the full traceback.

[0;31mSystemExit[0m[0;31m:[0m 0

SystemExit: 0

